Update workflow config files.

diff --git a/.github/workflows/pg-regress-emulator.yml b/.github/workflows/pg-regress-emulator.yml
--- a/.github/workflows/pg-regress-emulator.yml
+++ b/.github/workflows/pg-regress-emulator.yml
@@ -26,9 +26,22 @@ jobs:
           repository: postgres/postgres
           path: postgres
           ref: REL_16_0
+      - id: 'auth'
+        uses: 'google-github-actions/auth@v3'
+        with:
+          credentials_json: '${{ secrets.JSON_SERVICE_ACCOUNT_CREDENTIALS }}'
+          export_environment_variables: true
+      - name: 'Set up Cloud SDK'
+        uses: 'google-github-actions/setup-gcloud@v3'
+        with:
+          project_id: ${{ env.GOOGLE_CLOUD_PROJECT }}
       - uses: actions/setup-python@v5
         with:
           python-version: '3.9'
+      - name: Install jq
+        uses: dcarbone/install-jq-action@v3.2.0
+        with:
+          version: '1.7.1'
       - name: Setup psql
         run: |
           sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
@@ -51,7 +64,29 @@ jobs:
         run: |
           python start_test.py spanner_emulator --skip-container
           python compare_results.py expected/ results/
-      - name: Upload json result
+      - id: latest_gcs_file
+        name: Download the previous latest result
+        working-directory: ./postgres/src/test/regress/
+        run: |
+          if gcloud storage ls ${{env.GCS_BUCKET_PATH}}/results_latest.json; then
+            gcloud storage cp ${{env.GCS_BUCKET_PATH}}/results_latest.json
+            echo "has_latest_file=true" >> $GITHUB_OUTPUT
+          else
+            echo "has_latest_file=false" >> $GITHUB_OUTPUT
+            echo "upload_files=true" >> $GITHUB_OUTPUT
+          fi
+      - name: Compare json results
+        working-directory: ./postgres/src/test/regress/
+        if: needs.latest_gcs_file.outputs.has_latest_file == 'true'
+        run: |
+          prev_passed=$(jq -r '.overall.passed' results-latest.json)
+          curr_passed=$(jq -r '.overall.passed' results.json)
+          if (( $curr_passed < $prev_passed )); then
+            echo "Fail: $curr_passed is less than $prev_passed. Please check!"
+            exit 1
+          fi
+      - name: Upload results
         working-directory: ./postgres/src/test/regress/
         run: |
           gcloud storage cp results.json ${{env.GCS_BUCKET_PATH}}/results_$(date +%s).json
+          gcloud storage cp results.json ${{env.GCS_BUCKET_PATH}}/results_latest.json
